config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # Categories
  post 'categories/create'

  # User Items
  post    'user_items/create'
  delete  'user_items',        to: 'user_items#destroy'
  patch    'user_items',        to: 'user_items#update'
  get     'user_items/index'
  get     'user_items/edit'

  # Static Pages
  get     '/about',    to: 'static_pages#about'

  # Lists
  get     '/new_list',    to: 'lists#new'
  post    '/list',        to: 'lists#create'
  get     '/lists',       to: 'lists#index'
  get     'lists/show',   to: 'lists#show'
  get     'lists/edit'
  delete  'lists/delete', to: 'lists#destroy'
  
  # User sessions
  get    '/login',  to: "sessions#new"
  delete '/logout', to: "sessions#destroy"
  post   '/login',	to: "sessions#create"

  # User signup
  get  'users/new'
  post 'users/new', to: 'users#create'
  get  'users/show'
end

app/models/list.rb
class List < ApplicationRecord
	# Relationships
  belongs_to :user
  has_many 	 :list_items
  has_many 	 :items, :through => :list_items, source: :user_item

  #list item creation
  accepts_nested_attributes_for :list_items

	def total
	  total = 0.00
	  self.items.each do |item|
	    list_item = self.list_items.find_by(user_item_id: item.id)
	    total = total + (item.price * list_item.quantity)
	  end
	  total = '%.2f' % total
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :redirect_to_login

  def new
    @list = List.new
    @category = Category.new #may need to change this, seems to work for now
  end

  def create
    @list = List.new(name: list_params[:name], user_id: current_user.id)
    if @list.save
    	build_list_items
      flash[:success] = "List created!"
      redirect_to lists_show_path(@list)
    else
      flash.now[:warning] = @list.errors.full_messages
      render 'new'
    end
  end

  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find_by(id: params[:format]) # not sure why this isn't id by default
  end

  def edit
    @list = List.find_by(id: params[:format])
  end

  def update
  end

  def destroy
  end

  private
    def list_params
      params.require(:list).permit(:name, :list_item => [:user_item_id, :quantity],
                                          :category  => [:name])
    end

    def build_list_items
  		unless params[:list][:list_item].nil?
  			params[:list][:list_item].each do |l|
  				@list.list_items.create(user_item_id: l[:user_item_id], quantity: l[:quantity])
  			end
  		end
  	end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list_form.html.erb
<div class="new-list">

	<!-- New Items -->
	<%= render partial: 'shared/user_item_form' %>
	<!-- New Category -->	
	<%= render 'shared/new_category_form', locals: {category: @category} %>

	<%= form_for @list, url: list_path, html: {class: "form-signin"} do |f| %>
		<!-- Category -->
		<div class="categories">
			<% current_user.categories.each do |category| %>
				<h3 class="category">
				  <%= category.name %>
				</h3>
				<!-- User Items -->   
				<div class="dropdown-button" data-toggle="collapse" data-target="#<%= category.name_without_spaces %>">
					<span class="glyphicon glyphicon-chevron-down"></span>
				</div>
				<!-- Dropdown div -->
			 	<div id="<%= category.name_without_spaces %>" class="collapse">
			 		<div class="table-responsive">
			 			<!-- User Item table -->
					 		<table class='items' id='append<%= category.id %>'>
					 			<tr>
					 				<th>Add</th>
					 				<th>Name</th>
					 				<th>Price</th>
					 				<th>Qnty</th>
					 				<th>Edit</th>
					 				<th>Remove</th>
					 			</tr>
						   	<% category.user_items.each do |item| %>
						   		<% if item.included? %> <!--possibly filter this out in controller -->
						   			<tr id="item-row-<%=item.id%>"><%= render('shared/list_item_form', item: item, list: @list, f: f) %></tr>
						   		<% end %>
						  	<% end %>
						  </table>
					</div>
				</div>
			<% end %> <!-- current_user.categories -->
			<br>
			<div class='create-list'>
				<%= f.text_field :name, placeholder: "Name your list (optional)" %>
				<%= f.submit "Create List" %>
			</div>
		</div>
	<% end %>
</div>
<!-- dropdown button script -->
<script>
  $(document).ready(function () {
      $('.data-toggle').collapse();
  });
</script>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<%= @list.name %>

app/views/lists/index.html.erb
<div class="jumbotron">
	<div class="lists">
		<%= current_user.name + "'s lists" %>
		<ul>
		<% @lists.each_with_index do |list, n| %>
			<% list.name == "" ? name = "List #{n + 1}" : name = list.name %>
			<li>
				<%= link_to name, lists_show_path(params[:id] = list.id) %>
				<%= link_to "(edit)", 	lists_edit_path(params[:id] = list.id), class: "edit-list-links" %>
				<%= link_to "(delete)", "#", class: "edit-list-links" %>
			</li>
		<% end %>
		</ul>
	</div>
</div>

app/views/lists/new.html.erb
<% provide(:title, "New List") %>
<div class="jumbotron">
	<%= render 'lists/list_form' %>
</div>

app/views/lists/new.js.erb
$(document).ready(function () {
  addNewItemForm();
});

function addNewItemForm(){
	var categoryId = '<%= @category.id %>';
	$('#append' + categoryId).append("<%= j render 'shared/user_item_form', list: @list, category_id: @category.id %>");
}

app/views/lists/show.html.erb
<% provide(:title, "Your List") %>
<div class="jumbotron">
	<div class="new-list">
		<h2 id='list-name'><%= @list.name %></h2>
		<!-- Category -->
		<div class="categories">
			<% current_user.categories.each do |category| %>
				<h3 class="category">
				  <%= category.name %>
				</h3>
				<!-- User Items -->   
				<div class="dropdown-button" data-toggle="collapse" data-target="#<%= category.name_without_spaces %>">
					<span class="glyphicon glyphicon-chevron-down"></span>
				</div>
				<!-- Dropdown div -->
			 	<div id="<%= category.name_without_spaces %>" class="collapse">
			 		<div class="table-responsive">
			 			<!-- User Item table -->
					 		<table class='items' id='append<%= category.id %>'>
					 			<tr>
					 				<th>Name</th>
					 				<th>Price</th>
					 				<th>Qnty</th>
					 			</tr>
						   	<% @list.items.each do |item| %>
						   		<% if item.category == category %>
						   			<% list_item = @list.list_items.find_by(user_item_id: item.id) %>
							   		<tr>
							   			<th><%= item.name %></th>
							   			<th><%= item.price %></th>
							   			<th><%= list_item.quantity %></th>
							   		</tr>
							   	<% end %>
						  	<% end %>
						  </table>
					</div>
				</div>
			<% end %> <!-- current_user.categories -->
		</div>
		<h2>Total:<span id="total"> $<%= @list.total %></span></h2>
	</div>
</div>
<!-- dropdown button script -->
<script>
  $(document).ready(function () {
      $('.data-toggle').collapse();
  });
</script>