config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # Categories
  post 'categories/create'

  # User Items
  post    'user_items/create'
  delete  'user_items',        to: 'user_items#destroy'
  patch    'user_items',        to: 'user_items#update'
  get     'user_items/index'
  get     'user_items/edit'

  # Static Pages
  get     '/about',    to: 'static_pages#about'

  # Lists
  get     '/new_list',    to: 'lists#new'
  post    '/list',        to: 'lists#create'
  get     '/lists',       to: 'lists#index'
  get     'lists/show',   to: 'lists#show'
  get     'lists/edit'
  delete  'lists/delete', to: 'lists#destroy'
  
  # User sessions
  get    '/login',  to: "sessions#new"
  delete '/logout', to: "sessions#destroy"
  post   '/login',	to: "sessions#create"

  # User signup
  get  'users/new'
  post 'users/new', to: 'users#create'
  get  'users/show'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_logged_in.html.erb
<h1>Create a list!</h1>
<p class="lead">
	Begin making your new list here!
</p>
<p>
	<a class="btn btn-lg btn-success" href=<%= new_list_path %> role="button">Start</a>
</p>

app/views/static_pages/_home_not_logged_in.html.erb
<h1>Sign up today!</h1>
<p class="lead">
	Sign up in 30 seconds and start making your shopping list ASAP!
</p>
<p>
	<a class="btn btn-lg btn-success" href=<%= users_new_path %> role="button">Sign up</a>
</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
	<% if logged_in? %>
		<%= render 'static_pages/home_logged_in' %>
	<% else %>
		<%= render 'static_pages/home_not_logged_in' %>
	<% end %>
</div>

<div class="row marketing">
	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>More information can be written here for your convienence</p>
	</div>
	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>More information can be written here for your convienence</p>
	</div>
	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>More information can be written here for your convienence</p>
	</div>
	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>More information can be written here for your convienence</p>
	</div>
</div>