config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # Categories
  post 'categories/create'

  # User Items
  post    'user_items/create'
  delete  'user_items',        to: 'user_items#destroy'
  patch    'user_items',        to: 'user_items#update'
  get     'user_items/index'
  get     'user_items/edit'

  # Static Pages
  get     '/about',    to: 'static_pages#about'

  # Lists
  get     '/new_list',    to: 'lists#new'
  post    '/list',        to: 'lists#create'
  get     '/lists',       to: 'lists#index'
  get     'lists/show',   to: 'lists#show'
  get     'lists/edit'
  delete  'lists/delete', to: 'lists#destroy'
  
  # User sessions
  get    '/login',  to: "sessions#new"
  delete '/logout', to: "sessions#destroy"
  post   '/login',	to: "sessions#create"

  # User signup
  get  'users/new'
  post 'users/new', to: 'users#create'
  get  'users/show'
end

app/views/shared/_list_item_form.html.erb
<!-- Probably want to remove this from the view into controller or something -->
<% delete_message = "Prevent this item from showing up on future lists? (to simply exclude it from your current list, just leave it unchecked." %>

<%= f.fields_for l = list.list_items.build, index: l.id do |list_item| %>
	 	<td><%= list_item.check_box :user_item_id, { checked: false }, item.id, "nil" %></td> 
		<td><%= item.name %></td> 
		<td>$<%= number_with_precision(item.price, :precision => 2) %></td>
		<td><%= list_item.number_field :quantity, 
																	 	min: 1,
																	 	class: "num"%></td>
		<td><span class="glyphicon glyphicon-pencil"></span></td>
		<td>
			<%= link_to user_items_path(:user_item_id => item.id), method: :patch, confirm: 'Delete?', class: 'delete-link', 'data-message' => delete_message, 'data-severity' => 'danger', :remote => true do %>
				<span class="glyphicon glyphicon-remove"></span>
			<% end %>
		</td>
<% end %>

app/views/shared/_new_category_form.html.erb
<div id="new-category">
	<h4>New Category</h4>
	<%= form_for @category, url: categories_create_path, remote: true do |f| %>
		<%= f.text_field :name, placeholder: "Name", class: "txt" %>
		<%= f.submit "Create Category" %>
	<% end %>
</div>

app/views/shared/_user_item_form.html.erb
<div class="new-item">
	<h4>Add new items here:</h4>
	<%= form_for current_user.user_items.build, url: user_items_create_path, remote: true do |f| %>
		<%= f.text_field :name, placeholder: "Name", class: "txt" %>
		<%= f.number_field :price, min: 0.00, :step => "0.01", placeholder: "Price", class: "price"%>
		<%= f.select :category_id do %>
			<% current_user.categories.each do |category| %>
				<%= content_tag(:option, category.name, value: category.id) %>
			<% end %>
		<% end %>
		<%= f.submit "Add Item" %>
	<% end %>
</div>