config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # Categories
  post 'categories/create'

  # User Items
  post    'user_items/create'
  delete  'user_items',        to: 'user_items#destroy'
  patch    'user_items',        to: 'user_items#update'
  get     'user_items/index'
  get     'user_items/edit'

  # Static Pages
  get     '/about',    to: 'static_pages#about'

  # Lists
  get     '/new_list',    to: 'lists#new'
  post    '/list',        to: 'lists#create'
  get     '/lists',       to: 'lists#index'
  get     'lists/show',   to: 'lists#show'
  get     'lists/edit'
  delete  'lists/delete', to: 'lists#destroy'
  
  # User sessions
  get    '/login',  to: "sessions#new"
  delete '/logout', to: "sessions#destroy"
  post   '/login',	to: "sessions#create"

  # User signup
  get  'users/new'
  post 'users/new', to: 'users#create'
  get  'users/show'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	James Fonzone 2017
</footer>

app/views/layouts/_header.html.erb
<div class="header clearfix">
	<nav>
		<ul class="nav nav-pills pull-right">
			<li class="active" role="presentation">
				<%= link_to "New List", new_list_path %>
			</li>
			<li role="presentation">
				<%= link_to "My Items", '#' %>
			</li>
			<% if logged_in? %>
				<li role="presentation">
					<%= link_to "My Lists", lists_path %>
				</li>
				<li role="presentation">
					<%= link_to "Sign Out", logout_path, method: :delete %>
				</li>
			<% else %>
				<li role="presentation">
					<%= link_to "Sign In", login_path %>
				</li>
			<% end %>
		</ul>
	</nav>
	<a href=<%=root_url%>><h3 class="text-muted">Grocery App</h3></a>
</div>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<div class="container">
  		<%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    	<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
  </body>
</html>